export const userData = {
  totalCount: 5,
  list: [
    {
      service: 1,
      isConfirmed: false,
      mover: {
        id: 1,
        nickname: "김이사",
        imageUrl: null,
        career: 5,
        movingRequest: [],
        isDesignated: false,
        isFavorite: false,
        reviewCount: 3,
        favoriteCount: 12,
        confirmCount: 7,
        rating: {
          "1": 0,
          "2": 1,
          "3": 2,
          "4": 5,
          "5": 8,
          average: 4.2,
        },
      },
      id: 1,
      cost: 120000,
      comment: "12만원",
      movingDate: "2024-11-30T12:00:00.000Z",
      pickupAddress: "서울특별시 강남구 역삼동 123-456",
      dropOffAddress: "서울특별시 서초구 서초동 789-012",
    },
    {
      service: 2,
      isConfirmed: true,
      mover: {
        id: 2,
        nickname: "이현수",
        imageUrl: null,
        career: 8,
        movingRequest: [],
        isDesignated: false,
        isFavorite: true,
        reviewCount: 0,
        favoriteCount: 0,
        confirmCount: 0,
        rating: {
          "1": 0,
          "2": 0,
          "3": 0,
          "4": 0,
          "5": 0,
          average: null,
        },
      },
      id: 2,
      cost: 250000,
      comment: "25만원",
      movingDate: "2024-11-30T12:00:00.000Z",
      pickupAddress: "서울특별시 강남구 역삼동 123-456",
      dropOffAddress: "서울특별시 서초구 서초동 789-012",
    },
    {
      service: 0,
      isConfirmed: false,
      mover: {
        id: 3,
        nickname: "박이사",
        imageUrl: null,
        career: 10,
        movingRequest: [],
        isDesignated: true,
        isFavorite: false,
        reviewCount: 20,
        favoriteCount: 50,
        confirmCount: 30,
        rating: {
          "1": 0,
          "2": 1,
          "3": 3,
          "4": 10,
          "5": 25,
          average: 4.5,
        },
      },
      id: 3,
      cost: 300000,
      comment: "30만원",
      movingDate: "2024-11-30T12:00:00.000Z",
      pickupAddress: "서울특별시 강남구 역삼동 123-456",
      dropOffAddress: "서울특별시 서초구 서초동 789-012",
    },
    {
      service: 1,
      isConfirmed: true,
      mover: {
        id: 4,
        nickname: "최이사",
        imageUrl: null,
        career: 6,
        movingRequest: [],
        isDesignated: false,
        isFavorite: true,
        reviewCount: 15,
        favoriteCount: 25,
        confirmCount: 10,
        rating: {
          "1": 0,
          "2": 2,
          "3": 4,
          "4": 8,
          "5": 10,
          average: 4.3,
        },
      },
      id: 4,
      cost: 180000,
      comment: "18만원",
      movingDate: "2024-11-30T12:00:00.000Z",
      pickupAddress: "서울특별시 강남구 역삼동 123-456",
      dropOffAddress: "서울특별시 서초구 서초동 789-012",
    },
    {
      service: 2,
      isConfirmed: false,
      mover: {
        id: 5,
        nickname: "홍이사",
        imageUrl: null,
        career: 4,
        movingRequest: [],
        isDesignated: true,
        isFavorite: false,
        reviewCount: 5,
        favoriteCount: 8,
        confirmCount: 3,
        rating: {
          "1": 0,
          "2": 0,
          "3": 1,
          "4": 2,
          "5": 4,
          average: 4.0,
        },
      },
      id: 5,
      cost: 220000,
      comment: "22만원",
      movingDate: "2024-11-30T12:00:00.000Z",
      pickupAddress: "서울특별시 강남구 역삼동 123-456",
      dropOffAddress: "서울특별시 서초구 서초동 789-012",
    },
  ],
};
