const assets = {
  icons: {
    alarm: "/assets/icons/ic_alarm.svg",
    box: "/assets/icons/ic_box.svg",
    checkboxActive: "/assets/icons/ic_checkbox_active.svg",
    checkboxInactive: "/assets/icons/ic_checkbox_inactive.svg",
    chevronDown: "/assets/icons/ic_chevron_down.svg",
    chevronDownActive: "/assets/icons/ic_chevron_down_active.svg",
    chevronLeft: "/assets/icons/ic_chevron_left.svg",
    chevronRight: "/assets/icons/ic_chevron_right.svg",
    chevronUp: "/assets/icons/ic_chevron_up.svg",
    clip: "/assets/icons/ic_clip.svg",
    company: "/assets/icons/ic_company.svg",
    document: "/assets/icons/ic_document.svg",
    filterActive: "/assets/icons/ic_filter_active.svg",
    filterInactive: "/assets/icons/ic_filter_inactive.svg",
    home: "/assets/icons/ic_home.svg",
    info: "/assets/icons/ic_info.svg",
    likeActive: "/assets/icons/ic_like_active.svg",
    likeInactive: "/assets/icons/ic_like_inactive.svg",
    menu: "/assets/icons/ic_menu.svg",
    radioActive: "/assets/icons/ic_radio_active.svg",
    radioInactive: "/assets/icons/ic_radio_inactive.svg",
    search: "/assets/icons/ic_search.svg",
    starActive: "/assets/icons/ic_star_active.svg",
    starActiveHalf: "/assets/icons/ic_star_active_half.svg",
    starInactive: "/assets/icons/ic_star_inactive.svg",
    userProfile: "/assets/icons/ic_user_profile.svg",
    visibilityOff: "/assets/icons/ic_visibility_off.svg",
    visibilityOn: "/assets/icons/ic_visibility_on.svg",
    writing: "/assets/icons/ic_writing.svg",
    writingGray: "/assets/icons/ic_writing_gray.svg",
    x: "/assets/icons/ic_X.svg",
    xCircle: "/assets/icons/ic_X_circle.svg",
  },
  images: {
    avatarRed: "/assets/images/img_avatar_red.svg",
    imagePlaceholder: "/assets/images/img_image_placeholder.svg",
    landingMd01: "/assets/images/img_landing_md_01.svg",
    landingMd02: "/assets/images/img_landing_md_02.svg",
    landingMd03: "/assets/images/img_landing_md_03.svg",
    landingSm01: "/assets/images/img_landing_sm_01.svg",
    landingSm02: "/assets/images/img_landing_sm_02.svg",
    landingSm03: "/assets/images/img_landing_sm_03.svg",
    logo: "/assets/images/img_logo.svg",
    logoGoogle: "/assets/images/img_logo_google.svg",
    logoKakao: "/assets/images/img_logo_kakao.svg",
    logoMarkonly: "/assets/images/img_logo_markonly.svg",
    logoNaver: "/assets/images/img_logo_naver.svg",
    logoWordmark: "/assets/images/img_logo_wordmark.svg",
    movingTruck: "/assets/images/img_moving_truck.svg",
  },
};

export default assets;
